apiVersion: v1
kind: Service
metadata:
  name: demo-web
  namespace: netbox
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: demo-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web
  namespace: netbox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-web
  template:
    metadata:
      labels:
        app: demo-web
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"