apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: netbox
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: netbox
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17-alpine
        env:
        - name: POSTGRES_DB
          value: "netbox"
        - name: POSTGRES_USER
          value: "netbox"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: netbox-secrets
              key: db_password
        # Force Postgres to initialize inside a subfolder to dodge lost+found
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: default # AKS maps 'default' to 'managed-csi' Standard SSDs
      resources:
        requests:
          storage: 5Gi