apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbox-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/akshitpatel1732/SIT727-GitOps.git'
    targetRevision: HEAD
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: netbox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true